language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV=flake8
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6
          arch: ppc64le
          env: TOXENV=flake8
        - python: 2.7
          arch: ppc64le
          env: TOXENV=py27
        - python: 3.4
          arch: ppc64le
          env: TOXENV=py34
        - python: 3.5
          arch: ppc64le
          env: TOXENV=py35
        - python: 3.6
          arch: ppc64le
          env: TOXENV=py36
        - python: pypy
          env: TOXENV=pypy
          # - python: 3.6
          # env: TOXENV=docs
install:
  - pip install tox 
script:
  - tox
